import type { Metadata } from "next";

export const SITE_NAME = "Adeseun Oyeneye";
/**
 * Launching on Vercel's free subdomain rather than a custom domain for
 * now (direct instruction) — Vercel defaults an unclaimed project to
 * `<repo-name>.vercel.app`, so this predicts that value ahead of the
 * actual deploy. It's a prediction, not a confirmed value: if the
 * project gets a different name in the Vercel dashboard (or the name is
 * already taken and Vercel appends a suffix), update this to match the
 * real assigned URL once deployed — canonical links, the sitemap, and
 * every OG/Twitter absolute URL all derive from it.
 */
export const SITE_URL = "https://adeseun-website.vercel.app";
/**
 * Author-first, per direct instruction: her four real books lead
 * (naming all of them would blow the ~160-character SEO description
 * budget, so two representative titles stand in), her real professional
 * standing (Founder and Vice-President, Threesixty Africa Media —
 * corrected from an earlier "Threesixty Africa Group" guess, and from
 * "Vice-President" alone, once her own author bio confirmed both the
 * real name and that she founded it) is the credibility line, not the
 * headline — see library-content.ts and study-content.ts for the
 * research this is grounded in.
 */
const DEFAULT_DESCRIPTION =
  "Author of Think Before You Speak, Beyond the Mundane, Tranquility, and Black Is Beautiful. Founder and Vice-President, Threesixty Africa Media.";

type PageMetadataInput = {
  title: string;
  description?: string;
  path?: string; // e.g. "/library"
  noIndex?: boolean;
};

/**
 * Builds a Next.js Metadata object with consistent OG/Twitter defaults so
 * every page doesn't hand-roll its own social card config.
 * Usage: `export const metadata = pageMetadata({ title: "The Library", path: "/library" })`
 *
 * The OG/Twitter *image* is intentionally not set here — it's supplied by
 * the file-convention generators `app/opengraph-image.tsx` /
 * `app/twitter-image.tsx`, which Next merges into every route's metadata
 * automatically. That's one dynamically-rendered, always-present card
 * instead of a hard-coded path to a PNG that has to be kept in sync (the
 * old `/og-default.png` this replaced never existed on disk, so every
 * share fell back to no image).
 */
export function pageMetadata({
  title,
  description = DEFAULT_DESCRIPTION,
  path = "/",
  noIndex = false,
}: PageMetadataInput): Metadata {
  const url = new URL(path, SITE_URL).toString();
  const fullTitle = path === "/" ? SITE_NAME : `${title} — ${SITE_NAME}`;

  return {
    title: fullTitle,
    description,
    alternates: { canonical: url },
    robots: noIndex ? { index: false, follow: false } : { index: true, follow: true },
    openGraph: {
      title: fullTitle,
      description,
      url,
      siteName: SITE_NAME,
      locale: "en_US",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
    },
  };
}

/** Root metadata, spread into app/layout.tsx's `export const metadata`. */
export const rootMetadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: { default: SITE_NAME, template: `%s — ${SITE_NAME}` },
  description: DEFAULT_DESCRIPTION,
  // Favicon/apple-touch-icon are generated by app/icon.tsx and
  // app/apple-icon.tsx (next/og, same pattern as opengraph-image.tsx) —
  // Next.js picks both up automatically via file convention, nothing to
  // wire in here.
};

/**
 * JSON-LD structured data for the Person schema — every page can include
 * this via the <StructuredData> pattern below so search engines associate
 * the site with her as an author/executive, not just a generic business.
 */
export function personJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "Person",
    name: SITE_NAME,
    url: SITE_URL,
    jobTitle: "Author",
    description: DEFAULT_DESCRIPTION,
    sameAs: [] as string[], // fill in confirmed social/press profile URLs
  };
}

/** JSON-LD for an individual book — used on The Library's detail views. */
export function bookJsonLd(book: { title: string; description: string; isbn?: string; url: string }) {
  return {
    "@context": "https://schema.org",
    "@type": "Book",
    name: book.title,
    author: { "@type": "Person", name: SITE_NAME },
    description: book.description,
    ...(book.isbn ? { isbn: book.isbn } : {}),
    url: book.url,
  };
}
