import type { Metadata } from "next";

export const SITE_NAME = "Adeseun Oyeneye";
/**
 * Launching on Vercel's free subdomain rather than a custom domain for
 * now (direct instruction) — Vercel defaults an unclaimed project to
 * `<repo-name>.vercel.app`, so this predicts that value ahead of the
 * actual deploy. It's a prediction, not a confirmed value: if the
 * project gets a different name in the Vercel dashboard (or the name is
 * already taken and Vercel appends a suffix), update this to match the
 * real assigned URL once deployed — canonical links, the sitemap, and
 * every OG/Twitter absolute URL all derive from it.
 */
export const SITE_URL = "https://adeseun-website.vercel.app";
export const PERSON_ID = `${SITE_URL}/#adeseun`;
export const WEBSITE_ID = `${SITE_URL}/#website`;
/**
 * Executive-first, per direct instruction (superseding the earlier
 * author-first framing): the site's positioning now leads with her as a
 * Managing Director and entrepreneur, with authorship as one part of a
 * larger body of work rather than the headline. The role line itself is
 * reproduced from her own supplied website scope document, not invented
 * here — see the ADESEUN OYENEYE WEBSITE SCOPE BLUEPRINT's recommended
 * hero structure.
 */
const DEFAULT_DESCRIPTION =
  "Entrepreneur, media executive, architect, interior designer, and author — building businesses, shaping spaces, and telling African stories.";

type PageMetadataInput = {
  title: string;
  description?: string;
  path?: string; // e.g. "/books"
  noIndex?: boolean;
};

/**
 * Builds a Next.js Metadata object with consistent OG/Twitter defaults so
 * every page doesn't hand-roll its own social card config.
 * Usage: `export const metadata = pageMetadata({ title: "The Library", path: "/books" })`
 *
 * The OG/Twitter *image* is intentionally not set here — it's supplied by
 * the file-convention generators `app/opengraph-image.tsx` /
 * `app/twitter-image.tsx`, which Next merges into every route's metadata
 * automatically. That's one dynamically-rendered, always-present card
 * instead of a hard-coded path to a PNG that has to be kept in sync (the
 * old `/og-default.png` this replaced never existed on disk, so every
 * share fell back to no image).
 */
export function pageMetadata({
  title,
  description = DEFAULT_DESCRIPTION,
  path = "/",
  noIndex = false,
}: PageMetadataInput): Metadata {
  const url = new URL(path, SITE_URL).toString();
  const fullTitle = path === "/" ? SITE_NAME : `${title} — ${SITE_NAME}`;

  return {
    title: { absolute: fullTitle },
    description,
    alternates: { canonical: url },
    robots: noIndex
      ? { index: false, follow: false }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large",
            "max-snippet": -1,
            "max-video-preview": -1,
          },
        },
    openGraph: {
      title: fullTitle,
      description,
      url,
      siteName: SITE_NAME,
      locale: "en_NG",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description,
    },
  };
}

/** Root metadata, spread into app/layout.tsx's `export const metadata`. */
export const rootMetadata: Metadata = {
  metadataBase: new URL(SITE_URL),
  title: { default: SITE_NAME, template: `%s — ${SITE_NAME}` },
  description: DEFAULT_DESCRIPTION,
  alternates: {
    types: {
      "application/rss+xml": new URL("/feed.xml", SITE_URL).toString(),
    },
  },
  // Favicon/apple-touch-icon are generated by app/icon.tsx and
  // app/apple-icon.tsx (next/og, same pattern as opengraph-image.tsx) —
  // Next.js picks both up automatically via file convention, nothing to
  // wire in here.
};

/**
 * JSON-LD structured data for the Person schema — every page can include
 * this via the <StructuredData> pattern below so search engines associate
 * the site with her as an author/executive, not just a generic business.
 */
export function personJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "Person",
    "@id": PERSON_ID,
    name: SITE_NAME,
    url: SITE_URL,
    jobTitle: "Entrepreneur, Media Executive, Architect, Interior Designer, Author, Corporate Adviser",
    description: DEFAULT_DESCRIPTION,
    sameAs: [] as string[], // fill in confirmed social/press profile URLs
  };
}

/** Root graph used once in the shared layout so all page-level schema can
 * reference a stable WebSite and Person entity instead of redefining them. */
export function siteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "WebSite",
        "@id": WEBSITE_ID,
        url: SITE_URL,
        name: SITE_NAME,
        inLanguage: "en-NG",
        publisher: { "@id": PERSON_ID },
      },
      {
        ...personJsonLd(),
        "@context": undefined,
      },
    ],
  };
}

export function profilePageJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "ProfilePage",
    "@id": `${SITE_URL}/about/#profile`,
    url: `${SITE_URL}/about`,
    name: `${SITE_NAME} — Profile`,
    isPartOf: { "@id": WEBSITE_ID },
    mainEntity: { "@id": PERSON_ID },
    inLanguage: "en-NG",
  };
}

type ArticleMetadataInput = {
  title: string;
  description: string;
  slug: string;
  publishedAt: string;
  modifiedAt: string;
  image: string;
  topics: readonly string[];
  noIndex?: boolean;
};

export function articleMetadata(input: ArticleMetadataInput): Metadata {
  const path = `/ideas/${input.slug}`;
  const url = new URL(path, SITE_URL).toString();
  const image = new URL(input.image, SITE_URL).toString();
  const socialImage = new URL(`${path}/opengraph-image`, SITE_URL).toString();
  const fullTitle = `${input.title} — ${SITE_NAME}`;

  return {
    title: { absolute: fullTitle },
    description: input.description,
    alternates: { canonical: url },
    authors: [{ name: SITE_NAME, url: new URL("/about", SITE_URL).toString() }],
    robots: input.noIndex
      ? { index: false, follow: false }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-image-preview": "large",
            "max-snippet": -1,
            "max-video-preview": -1,
          },
      },
    openGraph: {
      type: "article",
      title: fullTitle,
      description: input.description,
      url,
      siteName: SITE_NAME,
      locale: "en_NG",
      publishedTime: input.publishedAt,
      modifiedTime: input.modifiedAt,
      authors: [new URL("/about", SITE_URL).toString()],
      tags: [...input.topics],
      images: [{ url: socialImage, width: 1200, height: 630, alt: input.title }, { url: image }],
    },
    twitter: {
      card: "summary_large_image",
      title: fullTitle,
      description: input.description,
      images: [socialImage],
    },
  };
}

type ArticleSchemaInput = ArticleMetadataInput & {
  dek: string;
  pillar: string;
  wordCount: number;
};

export function articleJsonLd(input: ArticleSchemaInput) {
  const articleUrl = new URL(`/ideas/${input.slug}`, SITE_URL).toString();
  const articleId = `${articleUrl}#article`;
  const pageId = `${articleUrl}#webpage`;
  const imageId = `${articleUrl}#primaryimage`;
  const breadcrumbId = `${articleUrl}#breadcrumb`;
  const imageUrl = new URL(input.image, SITE_URL).toString();
  const socialImageUrl = new URL(`/ideas/${input.slug}/opengraph-image`, SITE_URL).toString();

  return {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "BlogPosting",
        "@id": articleId,
        headline: input.title,
        description: input.description,
        url: articleUrl,
        mainEntityOfPage: { "@id": pageId },
        datePublished: input.publishedAt,
        dateModified: input.modifiedAt,
        author: { "@id": PERSON_ID },
        publisher: { "@id": PERSON_ID },
        image: [imageUrl, socialImageUrl],
        primaryImageOfPage: { "@id": imageId },
        inLanguage: "en-NG",
        articleSection: input.pillar,
        keywords: input.topics.join(", "),
        wordCount: input.wordCount,
        isPartOf: { "@id": WEBSITE_ID },
      },
      {
        "@type": "WebPage",
        "@id": pageId,
        url: articleUrl,
        name: input.title,
        description: input.dek,
        isPartOf: { "@id": WEBSITE_ID },
        breadcrumb: { "@id": breadcrumbId },
        primaryImageOfPage: { "@id": imageId },
        datePublished: input.publishedAt,
        dateModified: input.modifiedAt,
        inLanguage: "en-NG",
      },
      {
        "@type": "ImageObject",
        "@id": imageId,
        contentUrl: imageUrl,
        url: imageUrl,
        caption: input.title,
      },
      {
        "@type": "BreadcrumbList",
        "@id": breadcrumbId,
        itemListElement: [
          { "@type": "ListItem", position: 1, name: "Home", item: SITE_URL },
          { "@type": "ListItem", position: 2, name: "The Study", item: `${SITE_URL}/ideas` },
          { "@type": "ListItem", position: 3, name: input.title, item: articleUrl },
        ],
      },
    ],
  };
}

export function ideasCollectionJsonLd(
  articles: readonly { slug: string; title: string; publishedAt: string }[],
) {
  const url = `${SITE_URL}/ideas`;
  return {
    "@context": "https://schema.org",
    "@type": "CollectionPage",
    "@id": `${url}#collection`,
    url,
    name: "The Study — Ideas & Essays",
    description: "Essays on leadership, African media, architecture, purpose, and thoughtful communication.",
    isPartOf: { "@id": WEBSITE_ID },
    inLanguage: "en-NG",
    mainEntity: {
      "@type": "ItemList",
      itemListElement: articles.map((article, index) => ({
        "@type": "ListItem",
        position: index + 1,
        url: `${SITE_URL}/ideas/${article.slug}`,
        name: article.title,
        datePublished: article.publishedAt,
      })),
    },
  };
}

/** JSON-LD for an individual book — used on The Library's detail views. */
export function bookJsonLd(book: { title: string; description: string; isbn?: string; url: string }) {
  return {
    "@context": "https://schema.org",
    "@type": "Book",
    name: book.title,
    author: { "@type": "Person", name: SITE_NAME },
    description: book.description,
    ...(book.isbn ? { isbn: book.isbn } : {}),
    url: book.url,
  };
}
